# ansible-playbook create_avi_lsc_user.yml
---
- hosts: localhost
  connection: local

  vars_files:
    - vars/creds.yml

  vars:
    SeSshKey: "{{ lookup('file', '{{ SEKeyFile }}') }}"

  roles:
    - role: avinetworks.avisdk

  tasks:
    - name: Create a Cloud Connector User
      avi_cloudconnectoruser:
        controller: "{{ avi_credentials.controller }}"
        username: "{{ avi_credentials.username }}"
        password: "{{ avi_credentials.password }}"
        api_version: "{{ avi_credentials.api_version }}"
        private_key: "{{ SeSshKey }}"
        name: "{{ SEuser }}"
        # password: Abcd1234
  
    